version: '3'
services:
  webserver:
    image: airflow-container
    restart: always
    environment:
      - AIRFLOW_HOME=/opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: >
      bash -c "airflow db upgrade &&
               airflow scheduler & 
               airflow webserver"
