services:
  airflow-webserver:
    image: apache/airflow:2.7.1-python3.8
    container_name: airflow-webserver
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://omaragustinbrandan_coderhouse:5A6MEpt8Eg@data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default
    volumes:
      - ./airflow-config:/opt/airflow/config
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.8
    container_name: airflow-scheduler
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://omaragustinbrandan_coderhouse:5A6MEpt8Eg@data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com:5439/data-engineer-database
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow-config:/opt/airflow/config
    command: scheduler
